# Autogenerated wrapper script for Binaryen_jll for i686-w64-mingw32-cxx03
export libbinaryen, wasm2js, wasmas, wasmctoreval, wasmdis, wasmfuzztypes, wasmmerge, wasmmetadce, wasmopt, wasmreduce, wasmshell, wasmsplit

JLLWrappers.@generate_wrapper_header("Binaryen")
JLLWrappers.@declare_library_product(libbinaryen, "libbinaryen.dll")
JLLWrappers.@declare_executable_product(wasm2js)
JLLWrappers.@declare_executable_product(wasmas)
JLLWrappers.@declare_executable_product(wasmctoreval)
JLLWrappers.@declare_executable_product(wasmdis)
JLLWrappers.@declare_executable_product(wasmfuzztypes)
JLLWrappers.@declare_executable_product(wasmmerge)
JLLWrappers.@declare_executable_product(wasmmetadce)
JLLWrappers.@declare_executable_product(wasmopt)
JLLWrappers.@declare_executable_product(wasmreduce)
JLLWrappers.@declare_executable_product(wasmshell)
JLLWrappers.@declare_executable_product(wasmsplit)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbinaryen,
        "bin\\libbinaryen.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        wasm2js,
        "bin\\wasm2js.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmas,
        "bin\\wasm-as.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmctoreval,
        "bin\\wasm-ctor-eval.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmdis,
        "bin\\wasm-dis.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmfuzztypes,
        "bin\\wasm-fuzz-types.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmmerge,
        "bin\\wasm-merge.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmmetadce,
        "bin\\wasm-metadce.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmopt,
        "bin\\wasm-opt.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmreduce,
        "bin\\wasm-reduce.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmshell,
        "bin\\wasm-shell.exe",
    )

    JLLWrappers.@init_executable_product(
        wasmsplit,
        "bin\\wasm-split.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
